### PR TITLE
Task 7 use common scripts

### LINKED ISSUE #7: Use the common build scripts
Common build scripts are now stored in [scripts-build-go](https://github.com/crucibuild/scripts-build-go).

Make use of them in the template so that each new agent will be using them by default.

### PR DESCRIPTION
**Pull request by jpigree**
Closes #7

### CODE REVIEW

**Comment by jpigree** [comment]
When this is validated. I will port the fix on every existing agents.

**Comment by jpigree** [comment]
Erf, to make the build work here, we will have to merge the other pending pull request in [scripts-build-go](https://github.com/crucibuild/scripts-build-go).

**Comment by ccamel** [comment]
Yes, it would seems so.

**Comment by jpigree** [comment]
The error is very strange. The Makefile generated fails on "check" target because i can' find sdk-agent-go however it builds well before. Moreover the build on Go master works. ???? I am investigating.

**Comment by jpigree** [comment]
Okay. Found the issue.
=> https://github.com/golang/go/issues/12703
The gotype tool assumes that you have recently done a "go install" of all dependency packages that are imported by the source files that it type checks, since it parses the pkg.a object code files produced by the compiler in order to obtain type information. (This limitation is unfortunate and not well advertised.)

I removed install of dependenciesb because I thought it was uneeded. Somewhat this is fixed in Go's master branch.

**Comment by jpigree** [comment]
Okay. I documented myself a bit and go type seems to be overall a bad tool. It performs compile checks without the compiler which is useless for us as we build before linting. I flled a PR(https://github.com/crucibuild/scripts-build-go/pull/4) to deactivate it in scripts-build-go(the refactor immediately pays off it seems :) ).

**Review by ccamel — APPROVED** [review]
Good job !

**Pull request merged**
